# Generated by Django 3.2.5 on 2021-07-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_shoe_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='thumbnail',
            field=models.ImageField(default='shoe-thumbnail/default.png', upload_to='shoe-thumbnail/'),
        ),
    ]
