# Generated by Django 3.2.5 on 2021-07-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_shoeitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoeitem',
            name='picture',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shoe-thumbnail/'),
        ),
    ]
