# Generated by Django 3.2.5 on 2021-07-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210717_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoeitem',
            name='price',
        ),
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
