# Generated by Django 3.2.5 on 2021-07-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210717_1410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoeitem',
            unique_together={('shoe', 'color')},
        ),
    ]
