# Generated by Django 3.2.5 on 2021-07-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_shoeitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoeitem',
            name='size',
        ),
        migrations.AddField(
            model_name='shoeitem',
            name='size',
            field=models.ManyToManyField(to='product.Size'),
        ),
    ]
