# Generated by Django 3.2.5 on 2021-07-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210717_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['-dateAdded']},
        ),
    ]
